CREATE TABLE estudiantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    email VARCHAR(120) NOT NULL,
    codigo VARCHAR(12) NOT NULL,
    edad INTEGER NOT NULL,
    semestre INTEGER NOT NULL,
    carrera VARCHAR(60) NOT NULL,
    CONSTRAINT pk_estudiantes PRIMARY KEY (id),
    CONSTRAINT uk_estudiantes_email UNIQUE (email),
    CONSTRAINT uk_estudiantes_codigo UNIQUE (codigo)
);

CREATE INDEX idx_estudiantes_email ON estudiantes (email);
CREATE INDEX idx_estudiantes_codigo ON estudiantes (codigo);
